In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)

In [3]:
df=pd.read_csv('social.csv')
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
features=df.iloc[:,:-1].values
features

array([[15624510, 'Male', 19, 19000],
       [15810944, 'Male', 35, 20000],
       [15668575, 'Female', 26, 43000],
       ...,
       [15654296, 'Female', 50, 20000],
       [15755018, 'Male', 36, 33000],
       [15594041, 'Female', 49, 36000]], dtype=object)

In [5]:
label=df.iloc[:,-1].values

In [6]:
actual_features=features[:,2:4]
actual_features.shape

(400, 2)

In [7]:
# features scaling
from sklearn.preprocessing import StandardScaler
f_sc=StandardScaler()

In [9]:
# now training and testing data seperation
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(actual_features,label,test_size=0.2)

In [10]:
# here apply featuer scaling apply
final_train=f_sc.fit_transform(train_x)   # always max training data

In [11]:
final_train

array([[ 1.6721901 ,  1.65111334],
       [-0.63635205, -0.35602336],
       [-0.63635205,  1.44141249],
       [-0.44397354, -1.16486949],
       [-0.54016279,  1.95068598],
       [ 0.51791903,  1.89077145],
       [ 0.133162  ,  0.78235268],
       [-1.50205535, -1.28469855],
       [-0.25159502, -0.50580968],
       [ 0.71029754, -1.43448487],
       [-1.21348759, -1.43448487],
       [ 0.71029754, -0.7454678 ],
       [-1.02110907,  2.01060051],
       [ 0.22935126,  0.03342107],
       [ 1.09505456, -0.92521138],
       [ 0.42172977, -0.17627978],
       [ 0.32554051,  0.03342107],
       [ 0.71029754, -1.43448487],
       [ 0.90267605, -0.68555327],
       [-0.54016279, -1.55431393],
       [ 0.133162  ,  0.21316466],
       [ 0.8064868 , -1.43448487],
       [-0.82873056,  0.15325013],
       [-1.69443387, -0.62563874],
       [ 0.8064868 ,  1.41145522],
       [-1.79062312,  0.45282277],
       [-0.15540577, -0.29610883],
       [ 0.03697275, -0.26615157],
       [ 1.47981159,  0.36295098],
       [-1.79062312,  0.18320739],
       [-1.30967684,  0.57265183],
       [ 0.03697275,  1.2616689 ],
       [ 1.47981159, -1.0749977 ],
       [ 0.8064868 ,  0.36295098],
       [ 0.99886531, -1.10495497],
       [-0.82873056, -0.68555327],
       [-1.02110907, -1.16486949],
       [-1.11729833,  0.06337834],
       [-0.05921651,  0.30303645],
       [ 0.03697275,  0.03342107],
       [ 0.42172977, -0.47585242],
       [ 0.99886531, -1.19482676],
       [-1.11729833, -1.64418572],
       [-1.30967684, -1.52435666],
       [-0.15540577,  1.44141249],
       [ 0.133162  ,  1.08192532],
       [ 2.15313638, -0.83533959],
       [ 0.133162  ,  0.03342107],
       [-1.02110907,  0.78235268],
       [ 1.47981159,  2.19034409],
       [-1.79062312, -1.34461308],
       [-1.50205535, -0.20623704],
       [ 1.09505456,  0.54269456],
       [-0.92491982, -0.44589515],
       [-0.44397354,  1.29162617],
       [-1.02110907,  0.54269456],
       [-0.25159502, -0.14632251],
       [-1.59824461,  0.06337834],
       [-0.05921651, -0.38598063],
       [-1.50205535, -0.44589515],
       [ 0.03697275,  0.30303645],
       [ 0.22935126, -0.38598063],
       [ 1.38362233, -1.46444214],
       [-0.05921651,  2.22030136],
       [ 2.05694713,  0.54269456],
       [-0.63635205,  0.12329287],
       [ 0.22935126,  0.15325013],
       [ 0.03697275,  0.03342107],
       [-0.54016279, -1.55431393],
       [ 0.32554051,  0.06337834],
       [ 1.38362233,  1.32158343],
       [-0.82873056, -1.25474129],
       [-0.25159502, -0.3260661 ],
       [ 0.03697275, -0.56572421],
       [ 0.99886531,  0.78235268],
       [-0.63635205,  0.18320739],
       [ 0.03697275, -0.59568147],
       [ 0.90267605,  1.11188258],
       [ 0.99886531, -1.04504044],
       [-1.02110907, -0.47585242],
       [-0.92491982, -0.98512591],
       [-1.4058661 , -0.20623704],
       [ 0.90267605, -1.19482676],
       [ 0.03697275, -0.59568147],
       [-0.63635205, -0.05645072],
       [-0.05921651,  0.03342107],
       [-1.4058661 , -0.655596  ],
       [-0.15540577,  1.65111334],
       [-0.05921651, -1.10495497],
       [ 1.96075787, -0.68555327],
       [ 0.32554051,  0.06337834],
       [-1.11729833,  0.30303645],
       [ 0.32554051,  0.27307919],
       [-0.44397354, -0.29610883],
       [-0.63635205, -1.0749977 ],
       [-0.82873056,  0.39290824],
       [-0.82873056, -0.80538232],
       [-0.7325413 ,  0.27307919],
       [-0.05921651,  2.01060051],
       [ 1.57600085, -1.31465581],
       [ 1.6721901 , -0.92521138],
       [ 1.28743308, -1.40452761],
       [-1.88681238, -0.77542506],
       [ 0.90267605, -0.62563874],
       [-0.7325413 ,  1.11188258],
       [ 0.8064868 , -1.13491223],
       [ 0.22935126, -0.38598063],
       [ 0.32554051, -0.53576695],
       [ 1.86456861,  1.56124155],
       [-1.59824461,  0.54269456],
       [-0.54016279,  1.50132702],
       [-1.79062312,  0.00346381],
       [-0.05921651,  0.27307919],
       [-0.05921651,  0.00346381],
       [-0.25159502, -0.59568147],
       [ 0.8064868 ,  0.12329287],
       [-1.69443387,  0.12329287],
       [ 0.42172977,  2.37008768],
       [ 0.8064868 ,  0.27307919],
       [ 0.22935126,  0.24312192],
       [ 2.05694713, -0.83533959],
       [ 0.8064868 , -1.40452761],
       [-0.7325413 ,  1.95068598],
       [ 0.22935126, -0.3260661 ],
       [ 0.22935126, -0.38598063],
       [ 0.99886531,  1.83085692],
       [ 1.38362233,  2.40004494],
       [ 1.57600085,  1.02201079],
       [ 0.32554051, -0.20623704],
       [ 0.8064868 , -0.3260661 ],
       [-0.34778428,  1.3515407 ],
       [-0.25159502,  0.03342107],
       [ 2.05694713,  1.80089966],
       [-0.34778428, -0.80538232],
       [-0.92491982,  0.57265183],
       [ 2.15313638, -1.0749977 ],
       [-0.34778428,  0.06337834],
       [-1.88681238, -0.53576695],
       [ 0.22935126, -0.26615157],
       [ 1.09505456,  0.12329287],
       [ 1.76837936,  1.02201079],
       [ 0.32554051, -0.56572421],
       [-0.25159502,  2.31017315],
       [ 0.61410828, -0.92521138],
       [ 0.99886531, -0.86529685],
       [-0.25159502,  0.54269456],
       [ 1.09505456, -1.01508317],
       [ 1.57600085,  1.14183985],
       [ 0.99886531,  1.92072872],
       [ 0.90267605, -0.59568147],
       [-1.11729833,  1.44141249],
       [ 0.99886531,  2.04055777],
       [ 1.38362233, -0.95516864],
       [-1.11729833,  0.33299371],
       [-0.25159502, -1.43448487],
       [ 0.90267605,  1.05196805],
       [-1.79062312, -1.46444214],
       [-0.25159502, -1.34461308],
       [ 0.133162  ,  0.15325013],
       [ 0.51791903,  1.77094239],
       [ 0.42172977,  0.30303645],
       [ 0.8064868 ,  0.54269456],
       [-0.82873056,  0.39290824],
       [ 0.133162  ,  0.27307919],
       [ 0.133162  ,  0.03342107],
       [ 0.32554051, -0.7454678 ],
       [ 0.42172977,  1.02201079],
       [-0.82873056, -0.26615157],
       [-0.44397354, -0.86529685],
       [-0.92491982, -0.3260661 ],
       [-1.30967684, -1.28469855],
       [-1.30967684,  0.42286551],
       [ 0.03697275, -0.14632251],
       [-1.11729833, -1.61422846],
       [-0.15540577, -1.10495497],
       [ 1.09505456, -0.14632251],
       [-0.05921651,  0.69248088],
       [ 0.51791903,  1.2616689 ],
       [-0.25159502, -0.95516864],
       [ 0.32554051,  0.5127373 ],
       [-0.25159502,  1.14183985],
       [ 0.90267605, -1.0749977 ],
       [ 1.09505456,  0.48278004],
       [-0.15540577, -0.59568147],
       [ 0.42172977,  0.0933356 ],
       [-0.05921651,  0.12329287],
       [ 0.133162  , -0.83533959],
       [-0.25159502,  0.15325013],
       [ 0.32554051, -1.19482676],
       [-1.11729833, -0.53576695],
       [ 0.42172977,  1.14183985],
       [ 1.86456861, -1.31465581],
       [ 2.05694713, -1.22478402],
       [-1.30967684, -0.44589515],
       [-1.02110907,  0.60260909],
       [-1.02110907, -0.35602336],
       [-1.11729833, -0.80538232],
       [-0.25159502, -0.92521138],
       [ 1.28743308,  2.28021588],
       [-1.88681238,  0.48278004],
       [-0.25159502, -1.28469855],
       [ 1.09505456,  0.57265183],
       [-0.92491982, -0.3260661 ],
       [-0.92491982,  1.59119881],
       [-1.11729833, -1.04504044],
       [ 0.90267605, -1.40452761],
       [ 0.99886531,  0.60260909],
       [-0.05921651,  2.28021588],
       [ 2.15313638,  1.14183985],
       [-0.15540577, -0.47585242],
       [ 0.42172977,  0.60260909],
       [ 0.22935126, -0.14632251],
       [-1.02110907, -0.35602336],
       [ 0.22935126, -0.68555327],
       [ 0.133162  , -0.3260661 ],
       [-0.7325413 , -0.62563874],
       [-0.44397354, -0.02649346],
       [-1.21348759, -1.10495497],
       [ 0.03697275, -0.3260661 ],
       [-0.25159502,  0.06337834],
       [ 0.133162  , -0.83533959],
       [-0.05921651, -0.44589515],
       [-1.4058661 , -1.4943994 ],
       [ 0.42172977, -0.14632251],
       [ 0.42172977,  0.27307919],
       [-0.92491982, -0.77542506],
       [-0.92491982,  0.45282277],
       [-1.02110907, -1.58427119],
       [-0.15540577,  0.87222447],
       [ 0.42172977, -0.14632251],
       [-1.30967684, -1.40452761],
       [ 0.133162  ,  1.92072872],
       [-0.25159502, -0.68555327],
       [ 2.15313638,  0.96209626],
       [-0.92491982,  0.5127373 ],
       [-0.63635205,  0.57265183],
       [-0.82873056,  0.30303645],
       [ 1.38362233,  2.04055777],
       [-1.11729833, -1.19482676],
       [-1.02110907,  0.57265183],
       [ 1.96075787,  2.22030136],
       [ 0.32554051,  0.30303645],
       [-1.21348759,  0.27307919],
       [ 1.76837936, -0.29610883],
       [ 0.22935126,  0.15325013],
       [ 1.96075787, -1.40452761],
       [ 0.8064868 ,  0.78235268],
       [-0.05921651,  0.06337834],
       [-0.92491982,  0.27307919],
       [-0.05921651, -0.50580968],
       [ 0.42172977,  0.15325013],
       [ 0.42172977, -0.50580968],
       [ 0.32554051, -0.3260661 ],
       [-1.79062312, -1.52435666],
       [-0.7325413 ,  1.38149796],
       [-0.63635205, -1.55431393],
       [-1.69443387, -1.01508317],
       [-0.25159502, -1.4943994 ],
       [-1.69443387,  0.36295098],
       [-0.05921651,  0.15325013],
       [-1.11729833,  0.42286551],
       [-1.02110907,  0.42286551],
       [-1.88681238, -0.05645072],
       [ 1.57600085,  0.00346381],
       [-0.54016279,  1.41145522],
       [ 0.90267605,  1.29162617],
       [ 0.8064868 , -1.25474129],
       [ 2.05694713,  0.18320739],
       [ 0.99886531,  2.13042956],
       [-0.54016279,  0.48278004],
       [-0.15540577,  0.15325013],
       [-1.21348759,  0.5127373 ],
       [-0.05921651,  0.21316466],
       [-1.11729833, -1.58427119],
       [ 1.47981159,  1.02201079],
       [ 2.15313638, -0.83533959],
       [ 0.22935126,  1.11188258],
       [ 0.71029754, -1.31465581],
       [ 0.90267605, -1.4943994 ],
       [-0.7325413 ,  0.57265183],
       [ 1.96075787,  0.932139  ],
       [-0.92491982, -1.13491223],
       [-0.15540577,  2.22030136],
       [-0.82873056, -0.80538232],
       [-0.63635205,  0.03342107],
       [-0.05921651,  0.30303645],
       [-0.25159502,  0.63256636],
       [ 1.38362233,  0.60260909],
       [ 1.86456861,  0.12329287],
       [ 0.32554051,  0.06337834],
       [ 2.05694713,  2.19034409],
       [ 0.03697275, -0.44589515],
       [ 1.28743308,  1.92072872],
       [-0.25159502,  0.81230994],
       [-0.7325413 ,  0.5127373 ],
       [ 0.22935126,  2.16038683],
       [-0.54016279,  1.41145522],
       [-1.4058661 , -0.11636525],
       [ 0.32554051, -0.53576695],
       [-0.25159502,  0.06337834],
       [-1.4058661 ,  0.36295098],
       [-0.15540577, -0.20623704],
       [-0.63635205, -0.11636525],
       [-1.50205535, -1.55431393],
       [ 0.03697275, -0.26615157],
       [ 0.99886531, -1.10495497],
       [-0.44397354, -1.25474129],
       [ 2.15313638, -0.71551053],
       [-0.44397354, -0.56572421],
       [-1.79062312, -1.31465581],
       [-0.34778428, -1.34461308],
       [-0.25159502, -0.38598063],
       [ 0.8064868 , -0.86529685],
       [-0.25159502,  0.15325013],
       [-1.88681238,  0.36295098],
       [-0.7325413 ,  0.30303645],
       [-1.02110907, -0.38598063],
       [ 0.71029754,  1.83085692],
       [ 0.90267605, -1.34461308],
       [ 0.71029754,  0.27307919]])

In [12]:
# testing data 
final_test=f_sc.transform(test_x) # only testing data

In [13]:
# calling Ramdom Forest classifier
clf=RandomForestClassifier(n_estimators=30,criterion='entropy')

In [ ]:
# Now predict and check accuracy  score